### PR TITLE
[Feature 1] Profile Management [Edit Profile]

### PR DESCRIPTION
**Pull request by jenniferjinyoungyang**

### CODE REVIEW

**Review by A-Bunch-Of-Atoms — APPROVED** [review]
Looks fine

**Review by navarhontes — CHANGES_REQUESTED** [review]
Appreciate all the work you did, but holy crap this is too much for one pull request and I'm having trouble keeping up. Keep future PRs smaller if possible lmao; this would ideally be multiple pull requests. I think their recommendation was no more than 300 lines per pull request or something. 

Given the amount of stuff going on here, it would be helpful if you could explain what each file is and why it exists either in comments or in the review thread.

**Comment by jenniferjinyoungyang** [comment]
@navarhontes

main
AndroidManifest: This came with a new project created by the Android Studio. When I created a new activity (Edit Profile) using Android Studio, it was automatically updated to include the EditProfileActivity.  

main/java/com/courseproject/tindar

MainActivity: front-end implementation for the Main screen. It came with a new project created by the Android Studio, and I added a button so that by clicking it the user can navigate to the edit profile screen. 

usescases/editprofile
- EditProfileDsGateway: Interface for the data add/update/retrieval
- EditProfileInputBoundary: Interface for the use case interactor
- EditProfileInteractor: implementation for the use case interactor
- EditProfileResponseModel: Implementation for the returned data structure for the data retrieval

ui/editprofile
- EditProfileActivity: front-end implementation for the Edit Profile screen

controllers/editprofile
- EditProfileController: Implementation for the controller

ds
- DatabaseHelper: Implementation for the data add/update/retrieval. (This is not only for edit profile, so I did not create subfolder for the edit profile).

androidTest/java/com/courseproject/tindar
ds
- DatabaseHelperTest: Android Test for the DatabaseHelper

test/java/com/courseproject/tindar
controllers/editprofile
- EditProfileControllerUnitTest: Unit Test for the EditProfileController

usecases/editprofile
- EditProfileInteractorUnitTest: Unit Test for the EditProfileInteractor

main/res (There are frontend xmls)
drawable
- ic_edit: Edit Icon xml
- ic_save: Save Icon xml

layout
- activity_edit_profile: edit profile activity (screen) xml
- activity_main: main activity (screen) xml
- dropdown_item: dropdown menu xml

values
- strings: this collects string literals for in other xml files the string literal can be referred to by name attribute here. This is Android studio recommendation so I followed it.

**Review by candidcalcifer — APPROVED** [review]

**Comment by navarhontes** [comment]
Okay this is probably my fault for not specifying how specific you needed to be with the descriptions; most of that was info that I could glean from the class names. My main confusion is with the database, how that works, and how we intend to use it; my understanding is that we don't have a group consensus on how to handle that. 

I can approve this if other features are depending on this and this is bottlenecking the group's progress, but I'm otherwise somewhat inclined to discuss this as a group before merging this branch.

**Comment by navarhontes** [comment]
I'm approving this with the asterisk that there's a high probability of needing to significantly rewrite or even scrap much of the database stuff and any work that significantly depends on it; my understanding is that we don't have a group consensus on how to handle syncing and a database. We can discuss how we want to handle this on Thursday. In the meantime, I suspect that it would be good for you to focus on more backend stuff and decouple things from the database implementation where possible.

**Review by navarhontes — APPROVED** [review]
https://github.com/CSC207-2023Y-UofT/course-project-tindar/pull/24#issuecomment-1638992405

**Pull request merged**
