### PR TITLE
[Task 2] fixes github workflow

### LINKED ISSUE #22: [Task 2] Fix github workflow
fix github workflow so it builds, runs unit tests, and runs android tests whenever there is a push to any branch

### PR DESCRIPTION
**Pull request by jenniferjinyoungyang**
What:
Fix GitHub action so it builds, runs unit tests, and runs Android tests whenever there is a push to any branch

Why:
GitHub action given by the github-classroom[bot] was not working since the repository structure has changed to fit the Android app project. Github action needs to be fixed. Also, our project has Android tests to test database methods. Action to auto-run Android tests in the ci should be added.

Implementation Details:
build job builds the app and runs the units tests
android-test job runs the Android tests

### CODE REVIEW

**Comment by navarhontes** [comment]
Somewhat inclined to see if we can fix both autograders in one PR. If this isn't figured out by the time I'm feeling better then I can take a look at this.

**Comment by jenniferjinyoungyang** [comment]
Looks to be working now. Just to note, it takes forever to run the android-test since it takes time to start an emulator.

**Comment by navarhontes** [comment]
Some thoughts:
1. I might just be ignorant, but does the android-test part actually run anything? 
2. Have you tested this by doing stuff like pushing tests that should fail and checking that they fail?

**Comment by jenniferjinyoungyang** [comment]
1. There is one example test in the androidTest folder. This will be run by the android-test process.
2. There is one example unit test in the test folder. I just checked it is actually run by the build process.

**Comment by navarhontes** [comment]
You've tested or that it's actually testing the Android stuff, right I'm asking because I didn't actually see a run line in the yml file.

**Comment by jenniferjinyoungyang** [comment]
for the unit test, I did by testing test failure case. You can find it in the past actions list. 
for the android test, I believe there is one line in the run android-test, that is saying 1 test run.

**Comment by navarhontes** [comment]
Yes I saw that you double-checked the unit testing. Thank you for doing that. 

Is it straightforward for you to do something similar for android-test? I ask because I don't see any run line in the yml file, and I'm not sure if running android-test actually runs the tests right now.

**Comment by jenniferjinyoungyang** [comment]
done. you can see from the actions list. BTW, I left you a message in the discord. Can you please check it?

**Comment by navarhontes** [comment]
See it. Thanks for humoring me and for getting this working; it was bothering me haha.

**Review by navarhontes — APPROVED** [review]

**Review by kresimirgotovac — APPROVED** [review]

**Review by candidcalcifer — APPROVED** [review]

**Pull request merged**
