### PR TITLE
[Feature 90] adds functionality to edit display name on the Edit Profile screen

### LINKED ISSUE #90: [Feature 90] adds edit display name functionality in the edit profile screen
What:
adds edit display name functionality in the edit profile screen so users can edit their display names

### PR DESCRIPTION
**Pull request by jenniferjinyoungyang**
What:
adds functionality to edit the display name of the user in the Edit Profile screen

Why:
a user wants to edit his/her display name somewhere in the app

Implementation Details
Adds EditText to input display name. It throws an error if a user tries to submit the updated profile information without the display name inputted. Implementation for updating the display name is the same as other fields in the profile update. I just needed to add one extra attribute in the EditProfileRequestModel

Closes #90

### CODE REVIEW

**Comment by jenniferjinyoungyang** [comment]
This is still a draft since I want the PR https://github.com/CSC207-2023Y-UofT/course-project-tindar/pull/116 to be merged first before mergin this PR. This PR is built on top of PR https://github.com/CSC207-2023Y-UofT/course-project-tindar/pull/116.

**Comment by navarhontes** [comment]
This is me flagging that documentation and warnings should probably be prioritized over this since Myles didn't comment on this feature.

**Review by kresimirgotovac — DISMISSED** [review]
1000 lines added holy moly, need docs for main activity

**Comment by jenniferjinyoungyang** [comment]
> 1000 lines added holy moly, need docs for main activity

That's because I was working off the other branch with documentation. It looks better now.

**Review by candidcalcifer — DISMISSED** [review]

**Review by ABunchOfAtom — DISMISSED** [review]

**Review by ABunchOfAtom — DISMISSED** [review]

**Comment by navarhontes** [comment]
image

**Review by navarhontes — APPROVED** [review]

**Review by candidcalcifer — APPROVED** [review]

**Review by kresimirgotovac — APPROVED** [review]

**Pull request merged**
